version: 1
project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/application.lpk
  target_arch: amd64
update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: mealie
build:
  toolchains: []
  run_buildscript: false
images:
  - id: mealie
    target: service
    service: mealie
    source: ghcr.io/mealie-recipes/mealie
    channel: stable
    sort: semver
    tag_regex: '^v[0-9]+\.[0-9]+\.[0-9]+$'
    delivery:
      mode: mirror
      require_digest_match: true
stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: Mealie
    summary: 为全家打造的自托管食谱管理和膳食计划工具，支持网址导入、可视化编辑与 REST API。
